# 1. Foundations

In [ ]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)

`pd.Series` - 1D, column. Homogenous. 

`pd.DataFrame` - 2D. Collection of `pd.Series`

`pd.Index`

To construct: `pd.Series(data_sequence - tuple/list)`

In [2]:
pd.Series(range(3), dtype="int8")

0    0
1    1
2    2
dtype: int8

In [3]:
pd.Series(["apple", "banana", "orange"], name="fruit")

0     apple
1    banana
2    orange
Name: fruit, dtype: str

In [4]:
# DF using List of Lists
pd.DataFrame([
    [1, 2],
    [4, 8],
], columns=["col_a", "col_b"])

   col_a  col_b
0      1      2
1      4      8

In [5]:
# DF using dictionary
pd.DataFrame({
    "first_name": ["Jane", "John"],
    "last_name": ["Doe", "Smith"],
})

  first_name last_name
0       Jane       Doe
1       John     Smith

In [6]:
ser1 = pd.Series(range(3), dtype="int8", name="int8_col")
ser2 = pd.Series(range(3), dtype="int16", name="int16_col")
pd.DataFrame({ser1.name: ser1, ser2.name: ser2})

   int8_col  int16_col
0         0          0
1         1          1
2         2          2

Pandas creates a auto-numbered `pd.Index` - technically, `pd.RangeIndex`

In [7]:
# rows have names instead of numbers 0-2
pd.Series([4, 4, 2], index=["dog", "cat", "human"])

dog      4
cat      4
human    2
dtype: int64

In [8]:
# You can give name to index as well
index = pd.Index(["dog", "cat", "human"], name="animal")
pd.Series([4, 4, 2], name="num_legs", index=index)

animal
dog      4
cat      4
human    2
Name: num_legs, dtype: int64

In [9]:
pd.DataFrame([
    [24, 180],
    [42, 166],
], columns=["age", "height_cm"], index=["Jack", "Jill"])

      age  height_cm
Jack   24        180
Jill   42        166

`pd.Series.dtype` gives the type of data. 

`pd.Series.name` gives the name of the series. 

`pd.Series.shape`

`pd.Series.size` - number of elements

you can use `len(ser)` to get number of rows

In [10]:
index = pd.Index(["dog", "cat", "human"], name="animal")
ser = pd.Series([4, 4, 2], name="num_legs", index=index)
ser

animal
dog      4
cat      4
human    2
Name: num_legs, dtype: int64

In [11]:
ser.name

'num_legs'

In [12]:
ser.dtype

dtype('int64')

In [13]:
ser.index

Index(['dog', 'cat', 'human'], dtype='str', name='animal')

In [17]:
ser.shape

(3,)

In [18]:
ser.size

3

In [19]:
len(ser)

3

In [20]:
index = pd.Index(["Jack", "Jill"], name="person")
df = pd.DataFrame([
    [24, 180, "red"],
    [42, 166, "blue"],
], columns=["age", "height_cm", "favorite_color"], index=index)
df

        age  height_cm favorite_color
person
Jack     24        180            red
Jill     42        166           blue

`pd.DataFrame.dtypes`

`pd.DataFrame.index`

In [21]:
df.dtypes

age               int64
height_cm         int64
favorite_color      str
dtype: object

In [22]:
df.index

Index(['Jack', 'Jill'], dtype='str', name='person')

In [23]:
df.columns

Index(['age', 'height_cm', 'favorite_color'], dtype='str')

# 2. Selection and Assignment

In [24]:
ser = pd.Series(list("abc") * 3)
ser

0    a
1    b
2    c
3    a
4    b
5    c
6    a
7    b
8    c
dtype: str

In [30]:
ser[3] # returns String

'a'

In [31]:
ser[[3]] # rerturns Series

3    a
dtype: str

In [32]:
ser[[0, 2]]

0    a
2    c
dtype: str

In [33]:
ser[:3]

0    a
1    b
2    c
dtype: str

In [34]:
ser[-4:]

5    c
6    a
7    b
8    c
dtype: str

In [35]:
ser = pd.Series(range(3), index=["Jack", "Jill", "Jayne"])
ser

Jack     0
Jill     1
Jayne    2
dtype: int64

In [36]:
ser["Jill"]

np.int64(1)

**Integer argument selects value by label and not by position**

In [37]:
ser = pd.Series(list("abc"), index=[2, 42, 21])
ser

2     a
42    b
21    c
dtype: str

In [38]:
ser[2]

'a'

**Slicing works positionally**

In [39]:
ser[:2]

2     a
42    b
dtype: str

In [40]:
ser = pd.Series(["apple", "banana", "orange"], index=[0, 1, 1])
ser

0     apple
1    banana
1    orange
dtype: str

In [41]:
ser[1] # Returns a Series because of non-unique label

1    banana
1    orange
dtype: str

In [42]:
df = pd.DataFrame(np.arange(9).reshape(3, -1), columns=["a", "b", "c"])
df

   a  b  c
0  0  1  2
1  3  4  5
2  6  7  8

In [46]:
df["a"]

0    0
1    3
2    6
Name: a, dtype: int64

In [44]:
df[["a"]]

   a
0  0
1  3
2  6

In [47]:
df[["a", "b"]]

   a  b
0  0  1
1  3  4
2  6  7

**Slice argument selects from rows instead of columns**

In [48]:
df[:2]

   a  b  c
0  0  1  2
1  3  4  5

**Use `iloc` method to signal that you are using position based selection**

In [49]:
ser = pd.Series(["apple", "banana", "orange"], index=[0, 1, 1])
ser

0     apple
1    banana
1    orange
dtype: str

In [50]:
ser.iloc[1]

'banana'

In [51]:
ser.iloc[[0, 2]]

0     apple
1    orange
dtype: str

In [52]:
ser.iloc[:2]

0     apple
1    banana
dtype: str

In [53]:
df = pd.DataFrame(np.arange(20).reshape(5, -1), columns=list("abcd"))
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [54]:
df.iloc[2, 2]

np.int64(10)

In [55]:
df.iloc[:, 0]

0     0
1     4
2     8
3    12
4    16
Name: a, dtype: int64

In [56]:
df.iloc[0, :]

a    0
b    1
c    2
d    3
Name: 0, dtype: int64

In [57]:
df.iloc[:, [0]]

    a
0   0
1   4
2   8
3  12
4  16

In [58]:
df.iloc[[0], :]

   a  b  c  d
0  0  1  2  3

In [59]:
df.iloc[[0, 1], [-1, -2]]

   d  c
0  3  2
1  7  6

**Use `loc` method to select by label**

In [60]:
ser = pd.Series(["apple", "banana", "orange"], index=[0, 1, 1])
ser

0     apple
1    banana
1    orange
dtype: str

In [61]:
ser.loc[1]

1    banana
1    orange
dtype: str

In [62]:
ser = pd.Series([2, 2, 4], index=["dog", "cat", "human"], name="num_legs")
ser

dog      2
cat      2
human    4
Name: num_legs, dtype: int64

In [63]:
ser.loc["dog"]

np.int64(2)

In [64]:
ser.loc[["dog", "cat"]]

dog    2
cat    2
Name: num_legs, dtype: int64

In [65]:
ser.loc[:"cat"]

dog    2
cat    2
Name: num_legs, dtype: int64

In [66]:
values = ["Jack", "Jill", "Jayne"]
ser = pd.Series(values)
ser

0     Jack
1     Jill
2    Jayne
dtype: str

In [67]:
values[:2]

['Jack', 'Jill']

In [68]:
ser.iloc[:2]

0    Jack
1    Jill
dtype: str

**When using `loc` method, slicing matches by label. So if you were to say :2, it loops over label until it finds label 2, but because pandas isn't sure how many label 2's are there, it keeps looking until it finds a diff value**

In [69]:
ser.loc[:2]

0     Jack
1     Jill
2    Jayne
dtype: str

In [70]:
repeats_2 = pd.Series(range(5), index=[0, 1, 2, 2, 0])
repeats_2.loc[:2]

0    0
1    1
2    2
2    3
dtype: int64

In [75]:
ser = pd.Series(range(4), index=["zzz", "xxx", "xxx", "yyy"])
ser.loc[:"xxx"]

zzz    0
xxx    1
xxx    2
dtype: int64

When index labels have no determinate order, and you use slicing, it throws error

In [80]:
ser = pd.Series(range(4), index=["zzz", "xxx", "yyy", "xxx"])
ser.loc[:"xxx"]

KeyError: "Cannot get right slice bound for non-unique label: 'xxx'"

In [81]:
ser.loc["xxx"]

xxx    1
xxx    3
dtype: int64

In [82]:
df = pd.DataFrame([
    [24, 180, "blue"],
    [42, 166, "brown"],
    [22, 160, "green"],
], columns=["age", "height_cm", "eye_color"], index=["Jack", "Jill", "Jayne"])
df

       age  height_cm eye_color
Jack    24        180      blue
Jill    42        166     brown
Jayne   22        160     green

In [83]:
df.loc["Jayne", "eye_color"]

'green'

In [84]:
df.loc[:, "age"]

Jack     24
Jill     42
Jayne    22
Name: age, dtype: int64

In [85]:
df.loc["Jack", :]

age            24
height_cm     180
eye_color    blue
Name: Jack, dtype: object

In [86]:
df.loc[["Jack", "Jill"], ["age", "eye_color"]]

      age eye_color
Jack   24      blue
Jill   42     brown

In [87]:
df = pd.DataFrame([
    [24, 180, "blue"],
    [42, 166, "brown"],
    [22, 160, "green"],
], columns=["age", "height_cm", "eye_color"])
df

   age  height_cm eye_color
0   24        180      blue
1   42        166     brown
2   22        160     green

**`pd.Index.get_indexer` helps convert a label or list of labels into corresponding positions in `pd.Index`**

In [88]:
col_idxer = df.columns.get_indexer(["age", "eye_color"])
col_idxer

array([0, 2])

In [89]:
df.iloc[[0, 1], col_idxer]

   age eye_color
0   24      blue
1   42     brown

In [90]:
df[["age", "eye_color"]].iloc[[0, 1]]

   age eye_color
0   24      blue
1   42     brown

`pd.Index.get_indexer` approach is faster than using multiple steps. 

**Pandas evaluates expressions eagerly, it will do what you say, when you say it.** 

The opposite of **eager execution: Pandas** is **lazy execution: SQL Engine**

You declare what your result to look like, and the SQL database optimizes and executes the query.

`pd.DataFrame.filter` allows you to select from cols/rows

By default selects columns matching the label arguments. 

**Rows => `axis=0`**

**Columns => `axis=1`**

In [91]:
df = pd.DataFrame([
    [24, 180, "blue"],
    [42, 166, "brown"],
    [22, 160, "green"],
], columns=[
    "age",
    "height_cm",
    "eye_color"
], index=["Jack", "Jill", "Jayne"])
df

       age  height_cm eye_color
Jack    24        180      blue
Jill    42        166     brown
Jayne   22        160     green

In [92]:
df.filter(["age", "eye_color"])

       age eye_color
Jack    24      blue
Jill    42     brown
Jayne   22     green

In [94]:
df.filter(["Jack", "Jill"], axis=0)

Empty DataFrame
Columns: []
Index: [Jack, Jill, Jayne]

In [95]:
df.filter(["Jack", "Jill"])

Empty DataFrame
Columns: []
Index: [Jack, Jill, Jayne]

In [96]:
df.filter(like="_")

       height_cm eye_color
Jack         180      blue
Jill         166     brown
Jayne        160     green

In [97]:
df.filter(regex=r"^Ja.*(?<!e)$", axis=0)

      age  height_cm eye_color
Jack   24        180      blue

**`pd.DataFrame.select_dtypes`**

In [98]:
df = pd.DataFrame([
    [0, 1.0, "2"],
    [4, 8.0, "16"],
], columns=["int_col", "float_col", "string_col"])
df

   int_col  float_col string_col
0        0        1.0          2
1        4        8.0         16

In [99]:
df.select_dtypes("int")

   int_col
0        0
1        4

In [100]:
df.select_dtypes(include=["int", "float"])

   int_col  float_col
0        0        1.0
1        4        8.0

In [101]:
df.select_dtypes(exclude=["int", "float"])

  string_col
0          2
1         16

In [102]:
mask = [True, False, True]
ser = pd.Series(range(3))
ser

0    0
1    1
2    2
dtype: int64

In [103]:
ser[mask]

0    0
2    2
dtype: int64

In [104]:
ser.loc[mask]

0    0
2    2
dtype: int64

In [105]:
df = pd.DataFrame(np.arange(6).reshape(3, -1))
df

   0  1
0  0  1
1  2  3
2  4  5

DataFrame applies mask against rows by default

In [106]:
df[mask]

   0  1
0  0  1
2  4  5

In [107]:
col_mask = [True, False]
df.loc[mask, col_mask]

   0
0  0
2  4

In [108]:
df = pd.DataFrame([
    [24, 180, "blue"],
    [42, 166, "brown"],
    [22, 160, "green"],
], columns=["age", "height_cm", "eye_color"], index=["Jack", "Jill", "Jayne"])
df

       age  height_cm eye_color
Jack    24        180      blue
Jill    42        166     brown
Jayne   22        160     green

In [109]:
blue_eyes = df["eye_color"] == "blue"
blue_eyes

Jack      True
Jill     False
Jayne    False
Name: eye_color, dtype: bool

In [110]:
green_eyes = df["eye_color"] == "green"
green_eyes

Jack     False
Jill     False
Jayne     True
Name: eye_color, dtype: bool

In [111]:
mask = blue_eyes | green_eyes
mask

Jack      True
Jill     False
Jayne     True
Name: eye_color, dtype: bool

In [112]:
df[mask]

       age  height_cm eye_color
Jack    24        180      blue
Jayne   22        160     green

In [113]:
age_lt_40 = df["age"] < 40
age_lt_40

Jack      True
Jill     False
Jayne     True
Name: age, dtype: bool

In [114]:
height_gt_170 = df["height_cm"] > 170
height_gt_170

Jack      True
Jill     False
Jayne    False
Name: height_cm, dtype: bool

In [115]:
df[age_lt_40 & height_gt_170]

      age  height_cm eye_color
Jack   24        180      blue

In [116]:
df[~(age_lt_40 & height_gt_170)]

       age  height_cm eye_color
Jill    42        166     brown
Jayne   22        160     green

**`pd.MultiINdex` subclass of `pd.Index` supports hierarchical labels.**

`pd.MultiIndex.from_tuples` to cunstruct from tuples.

In [117]:
index = pd.MultiIndex.from_tuples([
    ("John", "Smith"),
    ("John", "Doe"),
    ("Jane", "Doe"),
    ("Stephen", "Smith"),
], names=["first_name", "last_name"])
ser = pd.Series(range(4), index=index)
ser

first_name  last_name
John        Smith        0
            Doe          1
Jane        Doe          2
Stephen     Smith        3
dtype: int64

In [118]:
ser.loc["John"]

last_name
Smith    0
Doe      1
dtype: int64

In [119]:
ser.loc[["John"]]

first_name  last_name
John        Smith        0
            Doe          1
dtype: int64

In [120]:
ser.loc[("Jane", "Doe")]

np.int64(2)

In [121]:
ser.loc[(["Jane"], "Doe")]

first_name  last_name
Jane        Doe          2
dtype: int64

In [122]:
ser.loc[[("John", "Smith"), ("Jane", "Doe")]]

first_name  last_name
John        Smith        0
Jane        Doe          2
dtype: int64

In [123]:
ser.loc[(slice(None), "Doe")]

first_name
John    1
Jane    2
dtype: int64

In [124]:
ser.loc[(slice(None), ["Doe"])]

first_name  last_name
John        Doe          1
Jane        Doe          2
dtype: int64

In [127]:
ixsl = pd.IndexSlice
ser.loc[ixsl[:, ["Doe"]]]

first_name  last_name
John        Doe          1
Jane        Doe          2
dtype: int64

In [125]:
alist = list("abc")
alist[:]

['a', 'b', 'c']

In [126]:
alist[slice(None)]

['a', 'b', 'c']

In [128]:
row_index = pd.MultiIndex.from_tuples([
    ("John", "Smith"),
    ("John", "Doe"),
    ("Jane", "Doe"),
    ("Stephen", "Smith"),
], names=["first_name", "last_name"])
col_index = pd.MultiIndex.from_tuples([
    ("music", "favorite"),
    ("music", "last_seen_live"),
    ("art", "favorite"),
], names=["art_type", "category"])
df = pd.DataFrame([
   ["Swift", "Swift", "Matisse"],
   ["Mozart", "T. Swift", "Van Gogh"],
   ["Beatles", "Wonder", "Warhol"],
   ["Jackson", "Dylan", "Picasso"],
], index=row_index, columns=col_index)
df

art_type                music                      art
category             favorite last_seen_live  favorite
first_name last_name
John       Smith        Swift          Swift   Matisse
           Doe         Mozart       T. Swift  Van Gogh
Jane       Doe        Beatles         Wonder    Warhol
Stephen    Smith      Jackson          Dylan   Picasso

In [129]:
row_idxer = (slice(None), "Smith")
col_idxer = (slice(None), "favorite")
df.loc[row_idxer, col_idxer]

art_type                music      art
category             favorite favorite
first_name last_name
John       Smith        Swift  Matisse
Stephen    Smith      Jackson  Picasso

In [130]:
df.loc[(slice(None), "Smith"), (slice(None), "favorite")]

art_type                music      art
category             favorite favorite
first_name last_name
John       Smith        Swift  Matisse
Stephen    Smith      Jackson  Picasso

Cost of mutating depends on two factors:

1. type of data in pd.Series
2. how many objects reference pd.Series

**CoW Copy on Write** Default behavior in pandas 3.0

In [132]:
ser = pd.Series(range(3), index=list("abc"))
ser

a    0
b    1
c    2
dtype: int64

In [133]:
ser.loc["b"] = 42
ser

a     0
b    42
c     2
dtype: int64

In [134]:
ser.iloc[2] = -42
ser

a     0
b    42
c   -42
dtype: int64

In [135]:
row_index = pd.MultiIndex.from_tuples([
    ("John", "Smith"),
    ("John", "Doe"),
    ("Jane", "Doe"),
    ("Stephen", "Smith"),
], names=["first_name", "last_name"])
col_index = pd.MultiIndex.from_tuples([
    ("music", "favorite"),
    ("music", "last_seen_live"),
    ("art", "favorite"),
], names=["art_type", "category"])
df = pd.DataFrame([
   ["Swift", "Swift", "Matisse"],
   ["Mozart", "T. Swift", "Van Gogh"],
   ["Beatles", "Wonder", "Warhol"],
   ["Jackson", "Dylan", "Picasso"],
], index=row_index, columns=col_index)
df

art_type                music                      art
category             favorite last_seen_live  favorite
first_name last_name
John       Smith        Swift          Swift   Matisse
           Doe         Mozart       T. Swift  Van Gogh
Jane       Doe        Beatles         Wonder    Warhol
Stephen    Smith      Jackson          Dylan   Picasso

In [136]:
df.loc[:, ("art", "museuems_seen")] = [1, 2, 4, 8]
df

art_type                music                      art
category             favorite last_seen_live  favorite museuems_seen
first_name last_name
John       Smith        Swift          Swift   Matisse             1
           Doe         Mozart       T. Swift  Van Gogh             2
Jane       Doe        Beatles         Wonder    Warhol             4
Stephen    Smith      Jackson          Dylan   Picasso             8

In [137]:
df = pd.DataFrame([[0, 1], [2, 4]], columns=list("ab"))
df

   a  b
0  0  1
1  2  4

In [138]:
(
    df
    .mul(2)
    .add(42)
)

    a   b
0  42  44
1  46  50

In [139]:
df2 = (
    df
    .mul(2)
    .add(42)
)
df2["assigned_c"] = df2["b"] - 3
df2

    a   b  assigned_c
0  42  44          41
1  46  50          47

**`pd.DataFrame.assign` allows method chaining while assignment**

In [140]:
(
    df
    .mul(2)
    .add(42)
    .assign(chained_c=lambda df: df["b"] - 3)
)

    a   b  chained_c
0  42  44         41
1  46  50         47

# 3. Data Types

In the beginning pandas was built on top of numpy. Poor strings support. No support for missinig values. Had to create workaround methods. 


pandas v0.23 - data types implemented using numpy capable of handling missing values.

pandas v1.0 - string data type. `numpy_nullable` or `pandas extension types`

pandas v2.0 - allows use of `Arrow` for data types. 

`pd.IntXXDtype()`

`pd.UIntXXDtype()`


`pd.Float64Dtype()` `pd.Float32Dtype()`

`pd.BooleanDtype`

`pd.StringDtype()`

In [142]:
pd.Series(range(3), dtype=pd.Int64Dtype())

0    0
1    1
2    2
dtype: Int64

In [143]:
pd.Series(range(3))

0    0
1    1
2    2
dtype: int64

In [144]:
pd.Series(range(3), dtype=pd.Int8Dtype())

0    0
1    1
2    2
dtype: Int8

In [145]:
pd.Series([1, pd.NA, 2], dtype=pd.Int64Dtype())

0       1
1    <NA>
2       2
dtype: Int64

In [146]:
pd.Series([1, None, 2], dtype=pd.Int64Dtype())

0       1
1    <NA>
2       2
dtype: Int64

In [167]:
pd.Series([3.14, .333333333, -123.456], dtype=pd.Float64Dtype())

0        3.14
1    0.333333
2    -123.456
dtype: Float64

In [170]:
pd.Series([3.14, None, pd.NA], dtype=pd.Float64Dtype())

0    3.14
1    <NA>
2    <NA>
dtype: Float64

**Python `float`  is actually an IEEE 754 `double`**

In [171]:
ser1 = pd.Series([1_000_000.123], dtype=pd.Float32Dtype())
ser2 = pd.Series([1_000_000.124], dtype=pd.Float32Dtype())
ser1.eq(ser2)

0    True
dtype: boolean

In [172]:
pd.Series([True, False, True], dtype=pd.BooleanDtype())

0     True
1    False
2     True
dtype: boolean

In [173]:
pd.Series([1, 0, 1], dtype=pd.BooleanDtype())

0     True
1    False
2     True
dtype: boolean

In [174]:
pd.Series([1, pd.NA, None], dtype=pd.BooleanDtype())

0    True
1    <NA>
2    <NA>
dtype: boolean

`pd.Series.str` is a accessor

`upper` `lower` `title` `contains`

In [175]:
pd.Series(["foo", "bar", "baz"], dtype=pd.StringDtype())

0    foo
1    bar
2    baz
dtype: string

In [176]:
ser = pd.Series(["xx", "YyY", "zZzZ"], dtype=pd.StringDtype())
ser.str.len()

0    2
1    3
2    4
dtype: Int64

In [177]:
ser.str.upper()

0      XX
1     YYY
2    ZZZZ
dtype: string

In [178]:
ser = pd.Series(["foo", "bar", "baz"], dtype=pd.StringDtype())
ser.str.contains("o")

0     True
1    False
2    False
dtype: boolean

In [179]:
ser.str.contains(r"^ba[rz]$", case=False, regex=True)

0    False
1     True
2     True
dtype: boolean

**Pandas adopted the numpy `np.nan` applicable only to floats to handle missing values in integers.**

So, for this reason

- int converts to float
- boolean converts to object

`pd.NaT` was created for DateTime

In [180]:
ser = pd.Series(range(3))
ser

0    0
1    1
2    2
dtype: int64

In [181]:
ser.iloc[1] = None
ser

0    0.0
1    NaN
2    2.0
dtype: float64

In [182]:
pd.isna(pd.Series([1, np.nan, 2]))

0    False
1     True
2    False
dtype: bool

In [183]:
pd.isna(pd.Series([1, pd.NA, 2], dtype=pd.Int64Dtype()))

0    False
1     True
2    False
dtype: bool

In [184]:
np.nan == np.nan

False

In [185]:
pd.NA == pd.NA

In [186]:
ser = pd.Series(range(3), dtype=pd.Int64Dtype())
ser

0    0
1    1
2    2
dtype: Int64

**`pd.NA`, `None` works only when you use `dtype=pd.BooleanDtype()`**

In [187]:
mask = pd.Series([True, pd.NA, False], dtype=pd.BooleanDtype())
ser[mask]

0    0
dtype: Int64

In [189]:
mask = pd.Series([True, pd.NA, False])
ser[mask]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [188]:
mask = pd.Series([True, None, False])
ser[mask]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [190]:
mask = pd.Series([True, None, False])
mask = mask.fillna(False).astype(bool)
ser[mask]

0    0
dtype: Int64

In [192]:
values = ["foo", "bar", "baz"]
values_ser = pd.Series(values, dtype=pd.StringDtype())

In [193]:
ser = values_ser.astype(pd.CategoricalDtype())
ser

0    foo
1    bar
2    baz
dtype: category
Categories (3, string): ['bar', 'baz', 'foo']

In [195]:
cat = pd.CategoricalDtype(values_ser)
ser = pd.Series(values, dtype=cat)
ser

0    foo
1    bar
2    baz
dtype: category
Categories (3, string): ['foo', 'bar', 'baz']

In [196]:
ser.iloc[2] = "foo"
ser

0    foo
1    bar
2    foo
dtype: category
Categories (3, string): ['foo', 'bar', 'baz']

In [197]:
ser.iloc[2] = "qux"

TypeError: Cannot setitem on a Categorical with a new category (qux), set the categories first

In [198]:
shirt_sizes = pd.Series(["S", "M", "L", "XL"], dtype=pd.StringDtype())
cat = pd.CategoricalDtype(shirt_sizes, ordered=True)
ser = pd.Series(["XL", "L", "S", "L", "S", "M"], dtype=cat)
ser < "L"

0    False
1    False
2     True
3    False
4     True
5     True
dtype: bool

In [200]:
accepted_values = pd.Series(["foo", "bar"], dtype=pd.StringDtype())
cat = pd.CategoricalDtype(accepted_values)
ser = pd.Series(["foo", "bar", "foo"], dtype=cat)
ser

0    foo
1    bar
2    foo
dtype: category
Categories (2, string): ['foo', 'bar']

In [201]:
ser.cat.codes

0    0
1    1
2    0
dtype: int8

In [202]:
ser.cat.categories

Index(['foo', 'bar'], dtype='string')

In [203]:
pd.Series(["foo", "bar", "baz"] * 100, dtype=pd.StringDtype()).memory_usage()

2532

In [204]:
pd.Series(["foo", "bar", "baz"] * 100, dtype=cat).memory_usage()

C:\Users\vinayd\AppData\Local\Temp\ipykernel_20256\4205643695.py:1: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  pd.Series(["foo", "bar", "baz"] * 100, dtype=cat).memory_usage()

556

In [205]:
pd.Series(["foo", "bar", pd.NA], dtype=pd.CategoricalDtype())

0    foo
1    bar
2    NaN
dtype: category
Categories (2, str): ['bar', 'foo']

In [206]:
values = pd.Series(["foo", "bar"], dtype=pd.StringDtype())
cat = pd.CategoricalDtype(values)
pd.Series(["foo", "bar", pd.NA], dtype=cat)

0     foo
1     bar
2    <NA>
dtype: category
Categories (2, string): ['foo', 'bar']

In [207]:
ser = pd.Series([
    "2024-01-01 00:00:00",
    "2024-01-02 00:00:01",
    "2024-01-03 00:00:02"
], dtype="datetime64[ns]")
ser

0   2024-01-01 00:00:00
1   2024-01-02 00:00:01
2   2024-01-03 00:00:02
dtype: datetime64[ns]

In [208]:
ser = pd.Series([
    "2024-01-01",
    "2024-01-02",
    "2024-01-03"
], dtype="datetime64[ns]")
ser

0   2024-01-01
1   2024-01-02
2   2024-01-03
dtype: datetime64[ns]

In [209]:
ser.iloc[1] = "2024-01-04 00:00:42"
ser

0   2024-01-01 00:00:00
1   2024-01-04 00:00:42
2   2024-01-03 00:00:00
dtype: datetime64[ns]

In [210]:
ser.dt.year

0    2024
1    2024
2    2024
dtype: int32

In [211]:
ser.dt.month

0    1
1    1
2    1
dtype: int32

In [212]:
ser.dt.day_of_week

0    0
1    3
2    2
dtype: int32

In [213]:
pd.Series([
    "2024-01-01 00:00:01",
    "2024-01-02 00:00:01",
    "2024-01-03 00:00:01"
], dtype=pd.DatetimeTZDtype(tz="UTC"))

0   2024-01-01 00:00:01+00:00
1   2024-01-02 00:00:01+00:00
2   2024-01-03 00:00:01+00:00
dtype: datetime64[ns, UTC]

In [214]:
pd.Series([
    "2024-01-01 00:00:01",
    "2024-01-02 00:00:01",
    "2024-01-03 00:00:01"
], dtype=pd.DatetimeTZDtype(tz="-05:00"))

0   2024-01-01 00:00:01-05:00
1   2024-01-02 00:00:01-05:00
2   2024-01-03 00:00:01-05:00
dtype: datetime64[ns, UTC-05:00]

In [215]:
ser_no_tz = pd.Series([
    "2024-01-01 00:00:00",
    "2024-01-01 00:01:10",
    "2024-01-01 00:02:42"
], dtype="datetime64[ns]")
ser_et = ser_no_tz.dt.tz_localize("America/New_York")
ser_et

0   2024-01-01 00:00:00-05:00
1   2024-01-01 00:01:10-05:00
2   2024-01-01 00:02:42-05:00
dtype: datetime64[ns, America/New_York]

In [216]:
ser_pt = ser_et.dt.tz_convert("America/Los_Angeles")
ser_pt

0   2023-12-31 21:00:00-08:00
1   2023-12-31 21:01:10-08:00
2   2023-12-31 21:02:42-08:00
dtype: datetime64[ns, America/Los_Angeles]

In [217]:
ser_pt.dt.normalize() # set to midnight

0   2023-12-31 00:00:00-08:00
1   2023-12-31 00:00:00-08:00
2   2023-12-31 00:00:00-08:00
dtype: datetime64[ns, America/Los_Angeles]

In [218]:
ser = pd.Series([
    "2024-01-01",
    None,
    "2024-01-03"
], dtype="datetime64[ns]")
ser

0   2024-01-01
1          NaT
2   2024-01-03
dtype: datetime64[ns]

In [219]:
pd.isna(ser)

0    False
1     True
2    False
dtype: bool

`ns` allows values between 1677-09-21 to 2264-04-11

Satarting with Pandas 3.0 you could specify other precisions `s` `ms` `us`

In [220]:
pd.Series([
    "1500-01-01 00:00:01",
    "2500-01-01 00:00:01",
], dtype="datetime64[ns]")

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1500-01-01 00:00:01

In [221]:
pd.Series([
    "1500-01-01 00:00:01",
    "2500-01-01 00:00:01",
], dtype="datetime64[us]")

0   1500-01-01 00:00:01
1   2500-01-01 00:00:01
dtype: datetime64[us]